-- MySQL Script generated by MySQL Workbench
-- Sun Jul 19 18:24:42 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inventory_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventory_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventory_management` DEFAULT CHARACTER SET utf8 ;
USE `inventory_management` ;

-- -----------------------------------------------------
-- Table `inventory_management`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management`.`groups` (
  `group_id` INT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(100) NOT NULL UNIQUE,
  `description` TEXT NULL,
  `status` TINYINT DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `is_deleted` ENUM('yes','no') NOT NULL DEFAULT 'no',
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory_management`.`cadres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management`.`cadres` (
  `cadre_id` INT NOT NULL AUTO_INCREMENT,
  `cadre_name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `status` TINYINT DEFAULT 1,
  PRIMARY KEY (`cadre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory_management`.`designations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management`.`designations` (
  `desig_id` INT NOT NULL AUTO_INCREMENT,
  `designation_name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `status` TINYINT DEFAULT 1,
  PRIMARY KEY (`desig_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory_management`.`internal_designations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management`.`internal_designations` (
  `internal_desig_id` INT NOT NULL AUTO_INCREMENT,
  `designation_name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `status` TINYINT DEFAULT 1,
  PRIMARY KEY (`internal_desig_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory_management`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `middle_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(80) NULL,
  `gen` VARCHAR(20) NULL,
  `dob` DATE NULL,
  `mobile_no` VARCHAR(15) NULL,
  `email_id` VARCHAR(100) NULL,
  `cadre_id` INT NULL,
  `desig_id` INT NULL,
  `internal_desig_id` INT NULL,
  `role` ENUM('ADMIN', 'INVENTORY_HEAD', 'USER') NOT NULL,
  `telephone_no` VARCHAR(15) NULL,
  `user_name` VARCHAR(30) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_gazetted` ENUM('yes', 'no') NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `is_deleted` ENUM('yes','no') NOT NULL DEFAULT 'no',
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `user_type` ENUM('permanent', 'temporary', 'generic') NULL,
  `group_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY unique_username (user_name),
  UNIQUE KEY unique_email (email_id),
  INDEX `fk_users_groups_idx` (`group_id` ASC) VISIBLE,
  INDEX `fk_users_cadres_idx` (`cadre_id` ASC) VISIBLE,
  INDEX `fk_users_designations_idx` (`desig_id` ASC) VISIBLE,
  INDEX `fk_users_internal_designations_idx` (`internal_desig_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_groups`
    FOREIGN KEY (`group_id`)
    REFERENCES `inventory_management`.`groups` (`group_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_cadres`
    FOREIGN KEY (`cadre_id`)
    REFERENCES `inventory_management`.`cadres` (`cadre_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_designations`
    FOREIGN KEY (`desig_id`)
    REFERENCES `inventory_management`.`designations` (`desig_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_internal_designations`
    FOREIGN KEY (`internal_desig_id`)
    REFERENCES `inventory_management`.`internal_designations` (`internal_desig_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory_management`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `status` TINYINT DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory_management`.`assets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management`.`assets` (
  `asset_id` INT NOT NULL AUTO_INCREMENT,
  `asset_name` VARCHAR(150) NOT NULL,
  `unit` VARCHAR(20) NOT NULL,
  `description` TEXT NULL,
  `status` TINYINT DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `is_deleted` ENUM('yes','no') NOT NULL DEFAULT 'no',
  PRIMARY KEY (`asset_id`),
  UNIQUE INDEX `uq_asset_name` (`asset_name` ASC) VISIBLE,
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory_management`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management`.`inventory` (
  `inventory_id` INT NOT NULL AUTO_INCREMENT,
  `asset_id` INT NULL,
  `sr_no` INT NOT NULL,
  `ledger_number` VARCHAR(50) NULL,
  `quantity_received` INT NULL,
  `quantity_available` INT NULL,
  `purchase_cost` DECIMAL(12,2) NULL,
  `purchase_date` DATE NULL,
  `received_by` INT NULL,
  `remarks` TEXT NULL,
  `status` TINYINT DEFAULT 1,
  `is_deleted` ENUM('yes','no') NOT NULL DEFAULT 'no',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `quantity_disposed` INT NULL,
  PRIMARY KEY (`inventory_id`),
  INDEX `fk_inventory_assets1_idx` (`asset_id` ASC) VISIBLE,
  INDEX `fk_inventory_received_by_idx` (`received_by` ASC) VISIBLE,
  CONSTRAINT `fk_inventory_assets`
    FOREIGN KEY (`asset_id`)
    REFERENCES `inventory_management`.`assets` (`asset_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inventory_received_by`
    FOREIGN KEY (`received_by`)
    REFERENCES `inventory_management`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory_management`.`asset_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management`.`asset_assignment` (
  `assignment_id` INT NOT NULL AUTO_INCREMENT,
  `inventory_id` INT NULL,
  `user_id` INT NULL,
  `quantity` INT NULL,
  `assigned_by` INT NULL,
  `assigned_date` DATE NULL,
  `return_date` DATE NULL,
  `remarks` TEXT NULL,
  `status` TINYINT DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`assignment_id`),
  INDEX `fk_assignment_inventory_idx` (`inventory_id` ASC) VISIBLE,
  INDEX `fk_asset_assignment_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_asset_assignment_users1_idx1` (`assigned_by` ASC) VISIBLE,
  CONSTRAINT `fk_assignment_inventory`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `inventory_management`.`inventory` (`inventory_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_assignment_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `inventory_management`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_assignment_assigned_by`
    FOREIGN KEY (`assigned_by`)
    REFERENCES `inventory_management`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory_management`.`transfer_requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management`.`transfer_requests` (
  `transfer_request_id` INT NOT NULL AUTO_INCREMENT,
  `assignment_id` INT NULL,
  `requested_by` INT NULL,
  `to_user` INT NULL,
  `quantity` INT NULL,
  `reason` TEXT NULL,
  `source_holder_status` TINYINT NULL,
  `destination_holder_status` TINYINT NULL,
  `status` TINYINT DEFAULT 1,
  `requested_at` TIMESTAMP NULL,
  `source_approved_at` TIMESTAMP NULL,
  `destination_approved_at` TIMESTAMP NULL,
  `remarks` TEXT NULL,
  PRIMARY KEY (`transfer_request_id`),
  INDEX `fk_transfer_assignment_idx` (`assignment_id` ASC) VISIBLE,
  INDEX `fk_transfer_requested_by_idx` (`requested_by` ASC) VISIBLE,
  CONSTRAINT `fk_transfer_assignment`
    FOREIGN KEY (`assignment_id`)
    REFERENCES `inventory_management`.`asset_assignment` (`assignment_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transfer_requested_by`
    FOREIGN KEY (`requested_by`)
    REFERENCES `inventory_management`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transfer_to_user`
    FOREIGN KEY (`to_user`)
    REFERENCES `inventory_management`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory_management`.`disposal_requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management`.`disposal_requests` (
  `disposal_request_id` INT NOT NULL AUTO_INCREMENT,
  `assignment_id` INT NULL,
  `requested_by` INT NULL,
  `quantity` INT NULL,
  `reason` TEXT NULL,
  `remarks` TEXT NULL,
  `disposed_at` TIMESTAMP NULL,
  PRIMARY KEY (`disposal_request_id`),
  INDEX `fk_disposal_assignment_idx` (`assignment_id` ASC) VISIBLE,
  INDEX `fk_disposal_requests_users1_idx` (`requested_by` ASC) VISIBLE,
  CONSTRAINT `fk_disposal_assignment`
    FOREIGN KEY (`assignment_id`)
    REFERENCES `inventory_management`.`asset_assignment` (`assignment_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_disposal_requested_by`
    FOREIGN KEY (`requested_by`)
    REFERENCES `inventory_management`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory_management`.`asset_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management`.`asset_history` (
  `history_id` INT NOT NULL AUTO_INCREMENT,
  `inventory_id` INT NULL,
  `performed_by` INT NULL,
  `action` ENUM('RECEIVED', 'ASSIGNED', 'TRANSFERRED', 'RETURNED', 'DISPOSED', 'UPDATED', 'CANCELLED', 'REJECTED') NULL,
  `quantity` INT NULL,
  `reference_table` VARCHAR(50) NULL,
  `reference_id` INT NULL,
  `remarks` TEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`history_id`),
  INDEX `fk_asset_history_inventory1_idx` (`inventory_id` ASC) VISIBLE,
  INDEX `fk_asset_history_users1_idx` (`performed_by` ASC) VISIBLE,
  CONSTRAINT `fk_history_inventory`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `inventory_management`.`inventory` (`inventory_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_performed_by_id`
    FOREIGN KEY (`performed_by`)
    REFERENCES `inventory_management`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory_management`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management`.`notifications` (
  `notification_id` INT NOT NULL AUTO_INCREMENT,
  `receiver_id` INT NULL,
  `title` VARCHAR(50) NULL,
  `message` TEXT NULL,
  `is_read` TINYINT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`notification_id`),
  INDEX `fk_notification_receiver_idx` (`receiver_id` ASC) VISIBLE,
  CONSTRAINT `fk_notifications_receiver`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `inventory_management`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
